# Dapr Secrets Component for Local Development (Minikube)
# Uses Kubernetes native Secrets for storing credentials
# Supports both local and cloud deployments

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
  # Services allowed to use this component
  - api-service
  - recurring-task-service
  - notification-service
  - audit-service
