"""ReminderLog database model.

This model tracks all reminder emails sent to users. It serves two purposes:
1. Prevent duplicate reminders (via UNIQUE constraint on task_id + reminder_datetime)
2. Provide audit trail for debugging and analytics

The UNIQUE constraint on (task_id, reminder_datetime) is our primary defense
against sending duplicate reminders, even if multiple agent instances run
concurrently.
"""

from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


class DeliveryStatus(str, Enum):
    """Email delivery status enumeration.

    Attributes:
        SENT: Email successfully sent via SMTP
        FAILED: Email failed to send after all retries
        BOUNCED: Email bounced (invalid recipient)
        RETRYING: Email send failed, will retry
    """
    SENT = "sent"
    FAILED = "failed"
    BOUNCED = "bounced"
    RETRYING = "retrying"


class ReminderLog(SQLModel, table=True):
    """Log of all reminder emails sent to users.

    This table is the source of truth for duplicate prevention. Before sending
    a reminder, the agent checks this table for an existing entry with the
    same task_id and reminder_datetime.

    The UNIQUE constraint ensures atomicity - if two agent instances try to
    insert the same reminder simultaneously, one will succeed and the other
    will fail gracefully (preventing duplicates).

    Attributes:
        id: Unique identifier (UUID auto-generated by database)
        task_id: Foreign key to tasks table
        user_id: User ID (denormalized for quick queries)
        reminder_datetime: When reminder was scheduled (in UTC)
        sent_at: When email was actually sent (in UTC)
        email_to: Recipient email address
        email_subject: Email subject line
        email_body: Email body content (for audit trail)
        delivery_status: Current delivery status (sent/failed/bounced/retrying)
        error_message: Error details if delivery failed
        retry_count: Number of retry attempts made
        next_retry_at: When to retry if status is 'retrying'
        created_at: Record creation timestamp
    """
    __tablename__ = "reminder_log"

    # Primary key (UUID auto-generated by PostgreSQL)
    id: Optional[str] = Field(default=None, primary_key=True)

    # Foreign key to tasks table
    task_id: int = Field(foreign_key="tasks.id", index=True)

    # User ID (denormalized for performance)
    user_id: str = Field(index=True)

    # When reminder was scheduled (UTC timezone)
    reminder_datetime: datetime = Field(nullable=False)

    # When email was actually sent (UTC timezone)
    sent_at: datetime = Field(default_factory=datetime.utcnow)

    # Email details
    email_to: str = Field(max_length=255)
    email_subject: str
    email_body: str

    # Delivery tracking
    delivery_status: str = Field(default=DeliveryStatus.SENT.value)
    error_message: Optional[str] = None
    retry_count: int = Field(default=0)
    next_retry_at: Optional[datetime] = None

    # Audit timestamp
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # NOTE: UNIQUE constraint on (task_id, reminder_datetime) is defined
    # in the database migration SQL, not in the model. See:
    # backend/migrations/001_add_reminder_tables.sql
    # CONSTRAINT unique_task_reminder UNIQUE(task_id, reminder_datetime)
